### ISSUE TITLE
Update faker library

### ISSUE THREAD

**Issue by oscles** [jackfranklin/test-data-bot#487] opened 2021-05-08 04:16 UTC
There are many functions in faker lib that not working for example images, some lorems. I saw that the faker last version is 5.5.3 but it is installed in test-data-bot the 4.1.0.

**Comment by babramczyk** [comment] 2021-05-12 13:20
+1. This makes it especially difficult if you also have `faker` installed as your own dep and are using TypeScript — even though this lib is using faker 4.1.0, the type for the `f` param for the `fake` function will use the latest `faker` you have installed in your project. So it will say things like `faker.random.uuid()` are deprecated, even though they’re not in the version of faker that `test-data-bot` is using

**Comment by DaniBedz** [comment] 2021-05-19 05:40
Running into the same issues here with date.soon() and datatype.number(). There are lots of great new methods in 5.5.3, would be great if we could get a bump.

**Comment by sekhavati** [comment] 2021-07-14 15:59
Any chance this open Dependabot PR (passing on CI) could be merged and a new version published @jackfranklin?

https://github.com/jackfranklin/test-data-bot/pull/521

**Comment by asile12** [comment] 2021-07-16 12:37
What if we make faker a peer dependency? So people can use the version they want

**Comment by oscles** [comment] 2021-07-26 21:18
that's an excellent idea @asile12 that we can install faker as a peer dependency.

**Comment by rluvaton** [comment] 2021-08-28 23:09
Any updarw?

**Comment by asile12** [comment] 2021-08-28 23:21
Until the problem is fixed, if you are using yarn you can force a version upgrade by adding resolutions to your package.json https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
(not sure about npm)

**Comment by jackfranklin** [comment] 2021-12-09 20:55
Hi all,

This is fixed in that v1.4.0 now ships with the latest version of Faker.

I'm also considering an API change here - opinions on #560 welcome. Thanks!

**Closed by jackfranklin** 2021-12-09 20:55 UTC
